[phases.setup]
nixPkgs = ["python311", "gcc", "openssl", "libffi", "zlib", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
